name: Lighthouse CI

on: [push]

jobs:
  lhci:
    name: Lighthouse
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Install Lighthouse CI
        run: npm install -g @lhci/cli@0.12.x

      - name: Create Report Directory
        run: mkdir -p report/lighthouse-report

      - name: Run Lighthouse CI
        run: |
          lhci healthcheck
          lhci autorun --config=.github/workflows/.lighthouserc.json
        env:
          LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}

      - name: List Lighthouse Report Contents
        run: ls -R report/lighthouse-report

      - name: Archive Lighthouse Report
        uses: actions/upload-artifact@v2
        with:
          name: lighthouse-report
          path: report/lighthouse-report
          if-no-files-found: error # 'warn' or 'ignore' are also available, defaults to `warn`
          retention-days: 5
