name: WRK Benchmark

on: [push]

jobs:
  benchmark:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install wrk
        run: |
          sudo apt-get update -q
          sudo apt-get install -y wrk

      - name: Run WRK Benchmark
        run: |
          # Read the list of URLs from urls.txt into an array
          mapfile -t urls < .github/workflows/urls.txt

          # Loop through each URL and run the benchmark
          for url in "${urls[@]}"; do
            echo "Benchmarking $url"
            wrk -t1 -c10 -d30s "$url" >> result.txt
            echo "Waiting for 10 seconds before the next test..."
            sleep 10
          done

      - name: Upload result.txt
        uses: actions/upload-artifact@v2
        with:
          name: benchmark-results
          path: result.txt
